src/Entity/Equipement.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EquipementRepository")
 */
class Equipement
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Theme", inversedBy="equipements")
     * @ORM\JoinColumn(nullable=false)
     */
    private $theme;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Categorie", inversedBy="equipements")
     * @ORM\JoinColumn(nullable=false)
     */
    private $categorie;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Type", inversedBy="equipements")
     */
    private $type;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $statut;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $commune;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $adresse;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $telephone;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $web;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $code_postal;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getTheme(): ?Theme
    {
        return $this->theme;
    }

    public function setTheme(?Theme $theme): self
    {
        $this->theme = $theme;

        return $this;
    }

    public function getCategorie(): ?Categorie
    {
        return $this->categorie;
    }

    public function setCategorie(?Categorie $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }

    public function getType(): ?Type
    {
        return $this->type;
    }

    public function setType(?Type $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getStatut(): ?string
    {
        return $this->statut;
    }

    public function setStatut(string $statut): self
    {
        $this->statut = $statut;

        return $this;
    }

    public function getCommune(): ?string
    {
        return $this->commune;
    }

    public function setCommune(?string $commune): self
    {
        $this->commune = $commune;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(?string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getTelephone(): ?int
    {
        return $this->telephone;
    }

    public function setTelephone(?int $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getWeb(): ?string
    {
        return $this->web;
    }

    public function setWeb(?string $web): self
    {
        $this->web = $web;

        return $this;
    }

    public function getCodePostal(): ?int
    {
        return $this->code_postal;
    }

    public function setCodePostal(?int $code_postal): self
    {
        $this->code_postal = $code_postal;

        return $this;
    }
}

src/Form/EquipementType.php
<?php

namespace App\Form;

use App\Entity\Equipement;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EquipementType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('statut')
            ->add('commune')
            ->add('adresse')
            ->add('telephone')
            ->add('web')
            ->add('code_postal')
            ->add('theme')
            ->add('categorie')
            ->add('type')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Equipement::class,
        ]);
    }
}

src/Controller/EquipementController.php
<?php

namespace App\Controller;

use App\Entity\Equipement;
use App\Form\EquipementType;
use App\Repository\EquipementRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/equipement")
 */
class EquipementController extends AbstractController
{
    /**
     * @Route("/", name="equipement_index", methods={"GET"})
     */
    public function index(EquipementRepository $equipementRepository): Response
    {
        return $this->render('equipement/index.html.twig', [
            'equipements' => $equipementRepository->findAll(),
        ]);
    }

    /**
     * @Route({"en": "/new", "fr": "/nouveau"}), name="equipement_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $equipement = new Equipement();
        $form = $this->createForm(EquipementType::class, $equipement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($equipement);
            $entityManager->flush();

            return $this->redirectToRoute('equipement_index');
        }

        return $this->render('equipement/new.html.twig', [
            'equipement' => $equipement,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="equipement_show", methods={"GET"})
     */
    public function show(Equipement $equipement): Response
    {
        return $this->render('equipement/show.html.twig', [
            'equipement' => $equipement,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="equipement_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Equipement $equipement): Response
    {
        $form = $this->createForm(EquipementType::class, $equipement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('equipement_index');
        }

        return $this->render('equipement/edit.html.twig', [
            'equipement' => $equipement,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="equipement_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Equipement $equipement): Response
    {
        if ($this->isCsrfTokenValid('delete'.$equipement->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($equipement);
            $entityManager->flush();
        }

        return $this->redirectToRoute('equipement_index');
    }
}

templates/equipement/_delete_form.html.twig
<form method="post" action="{{ path('equipement_delete', {'id': equipement.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ equipement.id) }}">
    <button class="btn">Delete</button>
</form>

templates/equipement/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/equipement/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Equipement{% endblock %}

{% block body %}
    <h1>Edit Equipement</h1>

    {{ include('equipement/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('equipement_index') }}">back to list</a>

    {{ include('equipement/_delete_form.html.twig') }}
{% endblock %}

templates/equipement/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Equipement index{% endblock %}

{% block body %}
    <h1>Equipement index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Statut</th>
                <th>Commune</th>
                <th>Adresse</th>
                <th>Telephone</th>
                <th>Web</th>
                <th>Code_postal</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for equipement in equipements %}
            <tr>
                <td>{{ equipement.id }}</td>
                <td>{{ equipement.name }}</td>
                <td>{{ equipement.statut }}</td>
                <td>{{ equipement.commune }}</td>
                <td>{{ equipement.adresse }}</td>
                <td>{{ equipement.telephone }}</td>
                <td>{{ equipement.web }}</td>
                <td>{{ equipement.codePostal }}</td>
                <td>
                    <a href="{{ path('equipement_show', {'id': equipement.id}) }}">show</a>
                    <a href="{{ path('equipement_edit', {'id': equipement.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('equipement_new') }}">Create new</a>
{% endblock %}

templates/equipement/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Equipement{% endblock %}

{% block body %}
    <h1>Create new Equipement</h1>

    {{ include('equipement/_form.html.twig') }}

    <a href="{{ path('equipement_index') }}">back to list</a>
{% endblock %}

templates/equipement/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Equipement{% endblock %}

{% block body %}
    <h1>Equipement</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ equipement.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ equipement.name }}</td>
            </tr>
            <tr>
                <th>Statut</th>
                <td>{{ equipement.statut }}</td>
            </tr>
            <tr>
                <th>Commune</th>
                <td>{{ equipement.commune }}</td>
            </tr>
            <tr>
                <th>Adresse</th>
                <td>{{ equipement.adresse }}</td>
            </tr>
            <tr>
                <th>Telephone</th>
                <td>{{ equipement.telephone }}</td>
            </tr>
            <tr>
                <th>Web</th>
                <td>{{ equipement.web }}</td>
            </tr>
            <tr>
                <th>Code_postal</th>
                <td>{{ equipement.codePostal }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('equipement_index') }}">back to list</a>

    <a href="{{ path('equipement_edit', {'id': equipement.id}) }}">edit</a>

    {{ include('equipement/_delete_form.html.twig') }}
{% endblock %}